name: CI-CD PIPELINE
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  IMAGE_NAME: ${{secrets.DOCKER_USERNAME}}

jobs: 
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: installdeps
        run: npm install
      - name: build site
        id : build-step
        run: |
          npm run build
          if [-f dist/index.html]; then
            echo "dist=true" >> $GITHUB_OUTPUT
            else echo "dist=false" >> $GITHUB_OUTPUT
            fi

  docker_build_push: 
         name: docker build & push
         runs-on: ubuntu-latest
         needs: build
         if: needs.build.outputs.dist_created == 'true'
         steps: 
          - uses: actions/checkout@v4
          - name : login to Docker Hub
            uses: docker/login-action@v3
            with: 
              username: ${{ secrets.DOCKER_USERNAME}}
              password: ${{ secrets.DOCKER_PASSWORD}}
          - name: build image
            run: |
               docker build -t ${{secrets.DOCKER_USERNAME}} / ci-cd-demo:latest .

          - name: push image
            run: |
              docker push ${{secrets.DOCKER_USERNAME}}/ci-cd-demo:latest
